default_stages: [push]
repos:
  # code formatter
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        stages: [push]

  # linter / code formatter
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        stages: [push]

  # misc static analyzers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
        stages: [push]
      - id: debug-statements
        stages: [push]
      - id: trailing-whitespace
        stages: [push]
      - id: end-of-file-fixer
        stages: [push]
      - id: check-yaml
        stages: [push]
      - id: check-added-large-files
        stages: [push]

  # linter / static analyzer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--max-line-length=100]
        stages: [push]

  # security static analyzer
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
      - id: python-bandit-vulnerability-check
        args: [-l, --recursive, -x, tests]
        files: .py$
        stages: [push]

  # type static analyzer
  - repo: git://github.com/luismayta/pre-commit-mypy
    rev: 'master'
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      stages: [push]

  # dockerfile linter
  - repo: https://git.shore.co.il/nimrod/docker-pre-commit.git
    rev: v0.3.0
    hooks:
      - id: hadolint
        stages: [push]
