language: python
dist: xenial
python:
  - "3.7"

# explicitly configure grype to cache the DB to a known directory
env:
  - GRYPE_DB_CACHE_DIR=/tmp/grype

# cache the grype directory so scans within the same-day will leverage the same vulnerability DB (better performance).
cache:
  directories:
    - /tmp/grype
    - $HOME/.local/bin

jobs:
  include:
    # 1. ... run linting, unit tests, etc., in previous stages...

    # 2. build & test the asset
    - name: Build & Test Docker Image
      install:
        # install grype and make available on path
        - mkdir -p $HOME/.local/bin && curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b $HOME/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
      script:
        # build the image
        - docker build -t myorg/myimage:latest .

        # scan the image for any known vulnerabilities; fail if any critical vulnerabilities are found
        - grype -v myorg/myimage:latest --fail-on critical

        # publish the image
        # - docker push myorg/myimage:latest ...
