cache:
  directories:
    - ./.tmp
    - $HOME/.cache/pre-commit

language: python
dist: xenial
python:
  - "3.7"

stages:
  - Code Quality Checks
  - Build Assets

install:
  - make bootstrap

jobs:
  include:
    # test code quality and correctness
    - stage: Code Quality
      name: Run Static Analysis
      script: make lint

    - name: Run Unit Tests
      script: make test

    # build & test the asset
    - stage: Build Assets
      name: Build & Test Docker Image
      script:
        - make build-image
        - make test-image
    # TODO: publish your asset
